### ISSUE TITLE
Can't manage to get IOS push notification working

### ISSUE THREAD

**Issue by Maxwell2022** [richsage/RMSPushNotificationsBundle#60]
I think it's missing some documentation about iOS and how to generate the certificate and passphrase. I've followed a neat video that it's explaining how to do ti (for another service, but still the same process): https://www.youtube.com/watch?v=12yjIm0Z8Cw
1. Generated CSR from keychain
2. upload the CSR to apple developer and download the generated certificate
3. Add this certificate to the keychain
4. Export the certificate (as p.12 format) setting a passphrase
5. Copy the exported certificate to the `app` folder (`app/certificates` for me)

Here is my configuration:

``` yaml
rms_push_notifications:
    android:
        gcm:
            api_key: xxxxxxx
            use_multi_curl: true # default is true
    ios:
        sandbox: true
        pem: "certificates/xxxx-apns-dev-cert.p12" # can be absolute or relative path (from app directory)
        passphrase: "xxxxx"
```

Now I have a p12 certification and the passphrase I've created. If I try to send a push notification I get the following error:

> PHP Warning:  stream_socket_client(): Unable to set local cert chain file `/var/www/xxxx/app/certificates/xxxxx-apns-dev-cert.p12'; Check that your cafile/capath settings include details of your certificate and its issuer in /var/www/xxxx/vendor/richsage/rms-push-notifications-bundle/RMS/PushNotificationsBundle/Service/OS/AppleNotification.php on line 196
